version: 0.2

env:
  secrets-manager:
    secret: arn:aws:secretsmanager:us-east-2:718028846669:secret:secretKey-PC7Nsx:secretKey
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - echo "Pre build stage..."
  build:
    commands:
      - echo "Build stage..."
      - echo $secret
      - yarn install
      - yarn lint
      - yarn test
  post_build:
    commands:
      - echo "Post build stage..."
      - echo Build completed on `date`

