version: 0.2

env:
  secrets-manager:
    secret: arn:aws:secretsmanager:us-east-2:718028846669:secret:secretKey-PC7Nsx:secretKey
phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  pre_build:
    commands:
      - echo "Pre build stage..."
      - echo "Logging in to Amazon ECR..."
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo "Build stage..."
      - echo $secret
      - yarn install
      - yarn lint
      - yarn test
      - docker build -t ci-cd-sample:latest .
      - docker tag ci-cd-sample:latest 718028846669.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ci-cd-sample:latest
  post_build:
    commands:
      - echo "Post build stage..."
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 718028846669.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ci-cd-sample:latest
      - printf '[{"name":"ci-cd-sample","imageUri":"%s"}]' 718028846669.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ci-cd-sample:latest > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
